### ISSUE TITLE
verify_dataset.sh failing due to missing file coco_annotations_minival.tgz

### ISSUE THREAD

**Issue by ipvirg** [mlperf/training_results_v0.6#23]
~/training_results_v0.6/NVIDIA/benchmarks/maskrcnn dataset download script is not downloading coco_annotations_minival.tgz file. The verify_dataset.sh script is failing due to missing file  coco_annotations_minival.tgz.

bash verify_dataset.sh
md5sum: coco_annotations_minival.tgz: No such file or directory
coco_annotations_minival.tgz: FAILED open or read
train2014.zip: OK
val2014.zip: OK
annotations_trainval2014.zip: OK
md5sum: WARNING: 1 listed file could not be read
FAILED

:~/training_results_v0.6/NVIDIA/benchmarks/maskrcnn/implementations$ cat hashes.md5
2d2b9d2283adb5e3b8d25eec88e65064  coco_annotations_minival.tgz
0da8c0bd3d6becc4dcb32757491aca88  train2014.zip
a3d79f5ed8d289b7a7554ce06a5782b3  val2014.zip
0a379cfc70b0e71301e0f377548639bd  annotations_trainval2014.zip

Is there an option where to download coco_annotations_minival.tgz file?

**Comment by jklingin** [comment]
This location should work: https://dl.fbaipublicfiles.com/detectron/coco/coco_annotations_minival.tgz

Source: https://github.com/mlperf/training/blob/138e2d3a12103c90d9b4b1739269425f93cdb20b/object_detection/download_dataset.sh

**Comment by ipvirg** [comment]
Thanks @jklingin. I got the file, rerun verify script with passed results.
