### ISSUE TITLE
NVIDIA dataset broken for GNMT? 

### ISSUE THREAD

**Issue by jeff-yajun-liu** [mlperf/training_results_v0.6#24]
training_results_v0.6/NVIDIA/benchmarks/gnmt/implementations/ verify_dataset.sh always came up with errors, is the dataset no longer valid? It is showing 12 GB after finishing data_download.sh script.

**Comment by ipvirg** [comment]
Had encounter similar scenario where the data downloaded was corrupted. Rename or delete the data directory, and then re-download the dataset fresh.

**Comment by jeff-yajun-liu** [comment]
I have tried that on two different systems with identical configurations, I am wondering if I can 1) reproduce the benchmark; 2) prep the dataset without script. 


    On Saturday, August 29, 2020, 11:27:56 AM PDT, ipvirg <notifications@github.com> wrote:  
 
 


Had encounter similar scenario where the data downloaded was corrupted. Rename or delete the data directory, and then re-download the dataset fresh.

**Comment by jeff-yajun-liu** [comment]
The issues resolved and we can close it off due to python SoftLink issue.
    On Saturday, August 29, 2020, 11:27:56 AM PDT, ipvirg <notifications@github.com> wrote:  
 
 


Had encounter similar scenario where the data downloaded was corrupted. Rename or delete the data directory, and then re-download the dataset fresh.

**Comment by jeff-yajun-liu** [comment]
> Had encounter similar scenario where the data downloaded was corrupted. Rename or delete the data directory, and then re-download the datase

**Comment by jeff-yajun-liu** [comment]
issue resolved by reconfiguring python soft link
